---
output: 
  html_document:
    toc: true
    toc_depth: 2
---

# PIGO Data Availability Statement (DAS)

## i. Overview
PIGO report provides a concise, high-level synthesis of evidence on public institutions around the world, designed to inform World Bank staff about the latest trends in institutional capacity, reforms and analytics. 

The data is obtained mainly from the Country-Level Institutional Assessment and Review (CLIAR) database and other World Bank indicators. The main audience of this report is World Bank staff and the data access is limited (internal use only)

## ii. Data

## Chapter 1: Global and Regional Trends in Institutional Capacity

**Filename : `cliar\db_variables.xlsx`**

-   Availability: World Bank Internal, based on public data.

-   Note: Raw. This is a code book.

-   Source: CLIAR Dashboard

-   URL: <https://w0lxdrconn01.worldbank.org/CLIAR/>

-   Access year: May 2025.

**Filename : `cliar\dynamic_ctf_032525.dta`**

-   Availability: World Bank Internal, based on public data.

-   Note: Raw. Data has not been modified.

-   Source: CLIAR Dashboard

-   URL: <https://w0lxdrconn01.worldbank.org/CLIAR/>

-   Access year: March 2025.

**Filename : `cliar\static_ctf_032525.dta`**

-   Availability: World Bank Internal, based on public data.

-   Note: Raw. Data has not been modified.

-   Source: CLIAR Dashboard

-   URL: <https://w0lxdrconn01.worldbank.org/CLIAR/>

-   Access year: March 2025.

**Filename : `cliar\static_ctf_012225.dta`**

-   Availability: World Bank Internal, based on public data.

-   Note: Raw. Data has not been modified.

-   Source: CLIAR Dashboard

-   URL: <https://w0lxdrconn01.worldbank.org/CLIAR/>

-   Access year: January 2025.

**Filename : `wb\client_countries.csv`**

-   Availability: Public.

-   Note: Data has been transformed with subject matter expertise

-   Source: File shared by Galileu Kim

-   URL: NA

-   Access year: February 2025.

**Filename : `wb\CLASS.xlsx`**

-   Availability: World Bank Public.

-   Note: Raw. Data has not been modified.

-   Source: World Bank Country and Lending Groups

-   URL: <https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups>

-   Access year: February 2025.

**Filename : `country_risk_index.xlsx`**

-   Availability: Fitch Solutions 

-   Note: Raw.

-   Source: Sourced from Fitch Solutions by Awais

-   URL: NA

-   Access year: 2025.

**Filename : `P_Data_Extract_From_World_Development_Indicators updated.xlsx`**

-   Availability: World Bank Public.

-   Note: Raw.

-   Source: WDI

-   URL: <https://databank.worldbank.org/source/world-development-indicators>

-   Access year: 2025.

## Chapter 2: Operational Engagements and Evidence on Institutional Capacity

**Filename : `boost\BOOST_country_data.xlsx`**

-   Availability: Internal use only.

-   Note: Data has not been modified.

-   Source: File shared by Massimo Mastruzzi on October 2024

-   URL: NA

-   Access year: October 2024

**Filename : `boost\budget_priorities.xlsx`**

-   Availability: Internal.

-   Note: Based on BOOST_country_data.xlsx, Lead economist Rita Ramalho used subject expertise to define list

-   Source: Internal

-   URL: NA

-   Access year: November 2024

**Filename : `gsps/GSPS_Indicators_Dataset_11_10_23.xlsx.`**

-   Availability: Public.

-   Note: Data has not been modified.

-   Source: Global Survey of Public Servants

-   URL: <https://www.globalsurveyofpublicservants.org/sites/default/files/2023-11/GSPS_Indicators_Dataset_11_10_23.xlsx>

-   Access year: May 2025.

**Filename : `wb/dgss.csv`.**

-   Availability: Public.

-   Note: Data has not been modified.

-   Source: GovTech Maturity Index.

-   URL: <https://datacatalogfiles.worldbank.org/ddh-published/0037889/DR0065450/WBG_GovTech%20Dataset_Dec2020.xlsx>

-   Access year: May 2025.



